### ISSUE TITLE
surplus requirements?

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam-manylinux-build#18]
I was able to build and upload 4.2a0 to pypi. However, I noticed something weird:

![image](https://user-images.githubusercontent.com/10515273/147624168-f993a080-3e6d-47d4-aeaa-86499b862827.png)

I wonder why numpy and pyparsing are installed? The latter makes me think these are requirements for *building* the wrapper, but I'm puzzled why they show up as requirements to use gtsam. Likewise, having numpy, while nice, is *not* a requirement for using gtsam I think.

**Comment by ProfFan** [comment]
`numpy` is a required component, `pyparsing` is not required, so we may want to make that a dev dependency instead? @varunagrawal

**Comment by dellaert** [comment]
> `numpy` is a required component, `pyparsing` is not required, so we may want to make that a dev dependency instead? @varunagrawal

Why is numpy required? Not questioning, just curious.

I like your proposed fix.

**Comment by ProfFan** [comment]
Because pybind11 converts everything in Eigen to numpy arrays

**Comment by varunagrawal** [comment]
Yup, Point2 and Point3 are just numpy arrays.

**Comment by varunagrawal** [comment]
`pyparsing` is a dev dependency but requirements.txt doesn't allow us to specify that. We should switch to the new `pyproject.toml` format.
