### ISSUE TITLE
Fix delocate

### ISSUE THREAD

**Issue by ProfFan** [borglab/gtsam-manylinux-build#21]
Delocate currently does not play well with our wheel because it has a wrong path detection mechanism.

I'll push a patch to fix this.

**Comment by dellaert** [comment]
@ProfFan Seems Action failed. I guess we'll also have to make an a3 version, as Pypi will not allow overwrite. However, I want to roll some changes into that as I write chapter 3, so we should hold off on that aspect of this. For now let's try and install 4.2a2 wheels on intel and M1 macs to see whether it's fixed.

FYI most important python version is 3.8 - version that robostack requires.

**Comment by ProfFan** [comment]
I am addressing this now

**Comment by ProfFan** [comment]
Fixed

**Comment by dellaert** [comment]
Fixed how? 
- Is the workflow fixed and so new mac wheels will be built correctly? 
- Does a PR still need to be merged before that's the case, in which cas ewhich PR?
- I assume I still need to talk to you get M1 wheels?

**Comment by dellaert** [comment]
@ProfFan can you answer questions above? I have no idea how the "delocate" issue was fixed, and I need to build new wheels soon.

**Comment by ProfFan** [comment]
> Fixed how?
> 
> * Is the workflow fixed and so new mac wheels will be built correctly?

Yes, that is correct, provided that `delocate` does not introduce new bugs

> * Does a PR still need to be merged before that's the case, in which case which PR?

No

> * I assume I still need to talk to you get M1 wheels?

Yes, that is correct, because M1 is not available on Actions.

**Comment by dellaert** [comment]
> > * Does a PR still need to be merged before that's the case, in which case which PR?
> No

I guess I don't understand. I don't see a PR that fixed the workflow. So how exactly was it fixed?

**Comment by ProfFan** [comment]
I directly pushed to master. https://github.com/borglab/gtsam-manylinux-build/compare/f7eeb05d91aa26570523f3ea4348eed991673817...master shows the actual diff.

Basically what I did is to use `install_name_tool` to fix the RPATH, so the dynamic loader will be able to correctly pick up the GTSAM library.

**Comment by dellaert** [comment]
Aha! I'd prefer if you do this via a PR so we can track and look over any changes. I was completely confused.
Thanks!

**Comment by ProfFan** [comment]
Sorry for the confusion, next time I will do this in a PR instead.

**Comment by johnwlambert** [comment]
Thanks for working on this @ProfFan. Did you have a chance to open an issue here describing the problem? https://github.com/matthew-brett/delocate

They've been pretty responsive to me in the past.
